export type EvidenceView = {
  id: string;
  seq: number;
  evidenceType: string;
  description: string;
  financialPeriod: string;
  sourceDocument: string;
  sourceSection: string;
  sourcePage: string | null;
};

export type OpportunityView = {
  id: string;
  seq: number;
  triggerId: string;
  opportunityName: string;
  serviceLine: string;
  agriCategory: string;
  finding: string;
  whyThisMatters: string;
  howWeCanAssist: string;
  recommendedSolution: string;
  valueProposition: string;
  clientValueLow: number;
  clientValueHigh: number;
  valueType: string;
  feeLow: number;
  feeHigh: number;
  roi: number | null;
  priority: string;
  timeline: string;
  confidence: string;
  overlapGroup: string | null;
  excludedFromTotals: boolean;
  capmatchEligible: boolean;
  capitalRequirementLow: number | null;
  capitalRequirementHigh: number | null;
  fundingCategories: string[];
  engagement: {
    duration: string;
    resources: string[];
    timeline: string;
    pricing: string;
  } | null;
  calculation: { basis: string; formula: string; assumptions: string[] } | null;
  evidence: EvidenceView[];
};

export type ReportView = {
  id: string;
  versionNo: number;
  clientId: string;
  clientName: string;
  industry: string;
  period: string;
  documentType: string;
  currency: string;
  reportDate: string | null;
  scopeNote: string;
  documents: string[];
  entities: string[];
  periods: string[];
  agriInsights: string[];
  basisAndLimitations: string[];
  topPriorities: { trigger_id: string; reason: string }[];
  informationRequests: { id: string; item: string; why: string; relatedTriggerId: string | null }[];
  clientValueLow: number;
  clientValueHigh: number;
  feeLow: number;
  feeHigh: number;
  overallRoi: number | null;
  opportunityCount: number;
  skillId: string | null;
  skillVersion: string | null;
  model: string | null;
  isArchived: boolean;
  createdAt: string;
  opportunities: OpportunityView[];
};
