import "server-only";
import type { ReportView } from "@/components/report/types";
import { loadAnalysis } from "./persist";

type Loaded = NonNullable<Awaited<ReturnType<typeof loadAnalysis>>>;

/** Maps the persisted record onto the serialisable shape the report renders. */
export function toReportView(analysis: Loaded): ReportView {
  return {
    id: analysis.id,
    versionNo: analysis.versionNo,
    clientId: analysis.clientId,
    clientName: analysis.clientName,
    industry: analysis.industry,
    period: analysis.period,
    documentType: analysis.documentType,
    currency: analysis.currency,
    reportDate: analysis.reportDate,
    scopeNote: analysis.scopeNote,
    documents: analysis.documents,
    entities: analysis.entities,
    periods: analysis.periods,
    agriInsights: analysis.agriInsights,
    basisAndLimitations: analysis.basisAndLimitations,
    topPriorities: analysis.topPriorities,
    informationRequests: analysis.informationRequests.map((r) => ({
      id: r.id,
      item: r.item,
      why: r.why,
      relatedTriggerId: r.relatedTriggerId,
    })),
    clientValueLow: analysis.clientValueLow,
    clientValueHigh: analysis.clientValueHigh,
    feeLow: analysis.feeLow,
    feeHigh: analysis.feeHigh,
    overallRoi: analysis.overallRoi,
    opportunityCount: analysis.opportunityCount,
    skillId: analysis.skillId,
    skillVersion: analysis.skillVersion,
    model: analysis.model,
    isArchived: analysis.isArchived,
    createdAt: analysis.createdAt,
    opportunities: analysis.opportunities.map((op) => ({
      id: op.id,
      seq: op.seq,
      triggerId: op.triggerId,
      opportunityName: op.opportunityName,
      serviceLine: op.serviceLine,
      agriCategory: op.agriCategory,
      finding: op.finding,
      whyThisMatters: op.whyThisMatters,
      howWeCanAssist: op.howWeCanAssist,
      recommendedSolution: op.recommendedSolution,
      valueProposition: op.valueProposition,
      clientValueLow: op.clientValueLow,
      clientValueHigh: op.clientValueHigh,
      valueType: op.valueType,
      feeLow: op.feeLow,
      feeHigh: op.feeHigh,
      roi: op.roi,
      priority: op.priority,
      timeline: op.timeline,
      confidence: op.confidence,
      overlapGroup: op.overlapGroup,
      excludedFromTotals: op.excludedFromTotals,
      capmatchEligible: op.capmatchEligible,
      capitalRequirementLow: op.capitalRequirementLow,
      capitalRequirementHigh: op.capitalRequirementHigh,
      fundingCategories: op.fundingCategories,
      engagement: op.engagement ?? null,
      calculation: op.calculation ?? null,
      evidence: op.evidence.map((e) => ({
        id: e.id,
        seq: e.seq,
        evidenceType: e.evidenceType,
        description: e.description,
        financialPeriod: e.financialPeriod,
        sourceDocument: e.sourceDocument,
        sourceSection: e.sourceSection,
        sourcePage: e.sourcePage,
      })),
    })),
  };
}
